#if UNITY_EDITOR
using Sirenix.Utilities.Editor;
using System;

namespace Util.Odin.Attributes {
	public static class IconsExtensions
	{
		public static EditorIcon ToEditorIcon(this Icons icon)
		{
			switch (icon)
			{
				case Icons.airplane:
					return EditorIcons.Airplane;
				case Icons.alertCircle:
					return EditorIcons.AlertCircle;
				case Icons.alertTriangle:
					return EditorIcons.AlertTriangle;
				case Icons.arrowDown:
					return EditorIcons.ArrowDown;
				case Icons.arrowLeft:
					return EditorIcons.ArrowLeft;
				case Icons.arrowRight:
					return EditorIcons.ArrowRight;
				case Icons.arrowUp:
					return EditorIcons.ArrowUp;
				case Icons.bell:
					return EditorIcons.Bell;
				case Icons.car:
					return EditorIcons.Car;
				case Icons.char1:
					return EditorIcons.Char1;
				case Icons.char2:
					return EditorIcons.Char2;
				case Icons.char3:
					return EditorIcons.Char3;
				case Icons.charGraph:
					return EditorIcons.CharGraph;
				case Icons.checkmark:
					return EditorIcons.Checkmark;
				case Icons.clock:
					return EditorIcons.Clock;
				case Icons.clouds:
					return EditorIcons.Clouds;
				case Icons.cloudsRainy:
					return EditorIcons.CloudsRainy;
				case Icons.cloudsRainySunny:
					return EditorIcons.CloudsRainySunny;
				case Icons.cloudsRainyThunder:
					return EditorIcons.CloudsRainyThunder;
				case Icons.cloudsThunder:
					return EditorIcons.CloudsThunder;
				case Icons.crosshair:
					return EditorIcons.Crosshair;
				case Icons.cut:
					return EditorIcons.Cut;
				case Icons.dayCalendar:
					return EditorIcons.DayCalendar;
				case Icons.download:
					return EditorIcons.Download;
				case Icons.eject:
					return EditorIcons.Eject;
				case Icons.eyeDropper:
					return EditorIcons.EyeDropper;
				case Icons.female:
					return EditorIcons.Female;
				case Icons.file:
					return EditorIcons.File;
				case Icons.fileCabinet:
					return EditorIcons.FileCabinet;
				case Icons.finnishBanner:
					return EditorIcons.FinnishBanner;
				case Icons.flag:
					return EditorIcons.Flag;
				case Icons.flagFinnish:
					return EditorIcons.FlagFinnish;
				case Icons.folder:
					return EditorIcons.Folder;
				case Icons.folderBack:
					return EditorIcons.FolderBack;
				case Icons.gKey:
					return EditorIcons.GKey;
				case Icons.globe:
					return EditorIcons.Globe;
				case Icons.gridBlocks:
					return EditorIcons.GridBlocks;
				case Icons.gridImageText:
					return EditorIcons.GridImageText;
				case Icons.gridImageTextList:
					return EditorIcons.GridImageTextList;
				case Icons.gridLayout:
					return EditorIcons.GridLayout;
				case Icons.hamburgerMenu:
					return EditorIcons.HamburgerMenu;
				case Icons.house:
					return EditorIcons.House;
				case Icons.image:
					return EditorIcons.Image;
				case Icons.imageCollection:
					return EditorIcons.ImageCollection;
				case Icons.info:
					return EditorIcons.Info;
				case Icons.letter:
					return EditorIcons.Letter;
				case Icons.lightBulb:
					return EditorIcons.LightBulb;
				case Icons.link:
					return EditorIcons.Link;
				case Icons.list:
					return EditorIcons.List;
				case Icons.loadingBar:
					return EditorIcons.LoadingBar;
				case Icons.lockLocked:
					return EditorIcons.LockLocked;
				case Icons.lockUnloacked:
					return EditorIcons.LockUnlocked;
				case Icons.magnifyingGlass:
					return EditorIcons.MagnifyingGlass;
				case Icons.male:
					return EditorIcons.Male;
				case Icons.marker:
					return EditorIcons.Marker;
				case Icons.maximize:
					return EditorIcons.Maximize;
				case Icons.microphone:
					return EditorIcons.Microphone;
				case Icons.minimize:
					return EditorIcons.Minimize;
				case Icons.minus:
					return EditorIcons.Minus;
				case Icons.mobilePhone:
					return EditorIcons.MobilePhone;
				case Icons.money:
					return EditorIcons.Money;
				case Icons.move:
					return EditorIcons.Move;
				case Icons.multiUser:
					return EditorIcons.MultiUser;
				case Icons.next:
					return EditorIcons.Next;
				case Icons.pacmanGhost:
					return EditorIcons.PacmanGhost;
				case Icons.paperclip:
					return EditorIcons.Paperclip;
				case Icons.pause:
					return EditorIcons.Pause;
				case Icons.pen:
					return EditorIcons.Pen;
				case Icons.penAdd:
					return EditorIcons.PenAdd;
				case Icons.penMinus:
					return EditorIcons.PenMinus;
				case Icons.play:
					return EditorIcons.Play;
				case Icons.plus:
					return EditorIcons.Plus;
				case Icons.podium:
					return EditorIcons.Podium;
				case Icons.previous:
					return EditorIcons.Previous;
				case Icons.receptionSignal:
					return EditorIcons.ReceptionSignal;
				case Icons.redo:
					return EditorIcons.Redo;
				case Icons.refresh:
					return EditorIcons.Refresh;
				case Icons.rotate:
					return EditorIcons.Rotate;
				case Icons.ruler:
					return EditorIcons.Ruler;
				case Icons.rulerRect:
					return EditorIcons.RulerRect;
				case Icons.settingsCog:
					return EditorIcons.SettingsCog;
				case Icons.shoppingBasket:
					return EditorIcons.ShoppingBasket;
				case Icons.shoppingCart:
					return EditorIcons.ShoppingCart;
				case Icons.singleUser:
					return EditorIcons.SingleUser;
				case Icons.smartPhone:
					return EditorIcons.SmartPhone;
				case Icons.sound:
					return EditorIcons.Sound;
				case Icons.speechBubbleRound:
					return EditorIcons.SpeechBubbleRound;
				case Icons.speechBubbleSquare:
					return EditorIcons.SpeechBubbleSquare;
				case Icons.speechBubblesRound:
					return EditorIcons.SpeechBubblesRound;
				case Icons.speechBubblesSquare:
					return EditorIcons.SpeechBubblesSquare;
				case Icons.starPointer:
					return EditorIcons.StarPointer;
				case Icons.stop:
					return EditorIcons.Stop;
				case Icons.stretch:
					return EditorIcons.Stretch;
				case Icons.table:
					return EditorIcons.Table;
				case Icons.tag:
					return EditorIcons.Tag;
				case Icons.testTube:
					return EditorIcons.TestTube;
				case Icons.timer:
					return EditorIcons.Timer;
				case Icons.trafficStopLight:
					return EditorIcons.TrafficStopLight;
				case Icons.transparent:
					return EditorIcons.Transparent;
				case Icons.tree:
					return EditorIcons.Tree;
				case Icons.triangleDown:
					return EditorIcons.TriangleDown;
				case Icons.triangleLeft:
					return EditorIcons.TriangleLeft;
				case Icons.triangleRight:
					return EditorIcons.TriangleRight;
				case Icons.triangleUp:
					return EditorIcons.TriangleUp;
				case Icons.undo:
					return EditorIcons.Undo;
				case Icons.upload:
					return EditorIcons.Upload;
				case Icons.wifiSignal:
					return EditorIcons.WifiSignal;
				case Icons.x:
					return EditorIcons.X;
				default:
					throw new ArgumentOutOfRangeException(nameof(icon), icon, null);
			}
		}
	}
}
#endif